services:
  web:
    build:
      context: .
    command: ["sh", "./start.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - 6379:6379

  celery:
    build:
      context: .
    command: celery -A core worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - db
    env_file:
      - .env

volumes:
  postgres_data:
