# Generated by Django 5.2.4 on 2025-07-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='Shopify Store URL')),
                ('cart_url', models.CharField(blank=True, max_length=512, verbose_name='Link to cart')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('no_products', 'No products'), ('error', 'Error')], default='pending', max_length=32, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
