# Generated by Django 5.2.4 on 2025-07-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error'), ('retrying', 'Retrying'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
